config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :potties

      resources :feedings

      resources :ownerships

      resources :dogs

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dogs#index"
  resources :potties
  resources :feedings
  resources :ownerships
  resources :dogs
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  # Direct associations

  has_many   :feedings,
             dependent: :destroy

  has_many   :potties,
             dependent: :destroy

  has_many   :ownerships,
             dependent: :destroy

  # Indirect associations

  has_many   :owners,
             through: :ownerships,
             source: :user

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/dogs_controller.rb
class Api::V1::DogsController < Api::V1::GraphitiController
  def index
    dogs = DogResource.all(params)
    respond_with(dogs)
  end

  def show
    dog = DogResource.find(params)
    respond_with(dog)
  end

  def create
    dog = DogResource.build(params)

    if dog.save
      render jsonapi: dog, status: :created
    else
      render jsonapi_errors: dog
    end
  end

  def update
    dog = DogResource.find(params)

    if dog.update_attributes
      render jsonapi: dog
    else
      render jsonapi_errors: dog
    end
  end

  def destroy
    dog = DogResource.find(params)

    if dog.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: dog
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[show edit update destroy]

  def index
    @q = Dog.ransack(params[:q])
    @dogs = @q.result(distinct: true).includes(:ownerships, :potties,
                                               :feedings, :owners).page(params[:page]).per(10)
  end

  def show
    @feeding = Feeding.new
    @potty = Potty.new
    @ownership = Ownership.new
  end

  def new
    @dog = Dog.new
  end

  def edit; end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to @dog, notice: "Dog was successfully created."
    else
      render :new
    end
  end

  def update
    if @dog.update(dog_params)
      redirect_to @dog, notice: "Dog was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @dog.destroy
    redirect_to dogs_url, notice: "Dog was successfully destroyed."
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name)
  end
end

app/views/dogs/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Dog #<%= dog.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= dog.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back dog, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_dog_url(dog), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to dog, method: :delete, data: { confirm: "Do you really want to delete this dog?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(dog.updated_at) %> ago
  </div>
</div>

app/views/dogs/_dog_feedings.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Feedings

    <a data-toggle="collapse" href="#dog_feedings_new_form">
      Add feeding
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dog.feedings.each do |feeding| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to feeding, feeding %>

        <%= link_to feeding, method: :delete, data: { confirm: "Do you really want to delete this feeding" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dog_feedings_new_form">
        <%= render partial: "dogs/dog_feedings_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dogs/_dog_feedings_new_form.html.erb
<%= form_with(model: @feeding, local: true) do |f| %>

  <%= f.hidden_field :dog_id, value: @dog.id %>

  <div class="form-group">
    <%= f.label :amount %>

    <%= f.text_field :amount, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :food_name %>

    <%= f.text_field :food_name, class: "form-control" %>
  </div>

  <%= f.submit "Create feeding", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dogs/_dog_owners.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Owners
  </div>

  <ul class="list-group list-group-flush">
    <% @dog.owners.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/dogs/_dog_ownerships.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Ownerships

    <a data-toggle="collapse" href="#dog_ownerships_new_form">
      Add ownership
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dog.ownerships.each do |ownership| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to ownership, ownership %>

        <% if current_user == ownership.user %>
          <%= link_to ownership, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dog_ownerships_new_form">
        <%= render partial: "dogs/dog_ownerships_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dogs/_dog_ownerships_new_form.html.erb
<%= form_with(model: @ownership, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.hidden_field :dog_id, value: @dog.id %>

  <%= f.submit "Create ownership", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dogs/_dog_potties.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Potties

    <a data-toggle="collapse" href="#dog_potties_new_form">
      Add potty
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dog.potties.each do |potty| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to potty, potty %>

        <%= link_to potty, method: :delete, data: { confirm: "Do you really want to delete this potty" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dog_potties_new_form">
        <%= render partial: "dogs/dog_potties_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dogs/_dog_potties_new_form.html.erb
<%= form_with(model: @potty, local: true) do |f| %>

  <%= f.hidden_field :dog_id, value: @dog.id %>

  <div class="form-group">
    <%= f.label :pee_or_poo %>

    <%= f.text_field :pee_or_poo, class: "form-control" %>
  </div>

  <%= f.submit "Create potty", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dogs/_dogs_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "dogs_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :owners_email_cont, "Owners email contains" %>
    <%= f.text_field :owners_email_cont, :class => "form-control", :placeholder => "Owners email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/dogs" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#dogs_filters">
  Show filters
</a>

app/views/dogs/_form.html.erb
<% was_validated = dog.errors.any? %>

<%= form_with(model: dog, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = dog.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% dog.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/dogs/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Dog #<%= @dog.id %>
      </h2>

      <div class="card-body">
        <%= render "form", dog: @dog %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Dogs

      <%= link_to new_dog_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "dogs/dogs_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Dogs

        <%= link_to new_dog_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @dogs, partial: "list_item", as: :dog %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @dogs, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Dog
      </h2>

      <div class="card-body">
        <%= render "form", dog: @dog %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @dog, partial: "card", as: :dog %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dogs/dog_ownerships" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dogs/dog_potties" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dogs/dog_feedings" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dogs/dog_owners" %>
  </div>
</div>