config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :potties

      resources :feedings

      resources :ownerships

      resources :dogs

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dogs#index"
  resources :potties
  resources :feedings
  resources :ownerships
  resources :dogs
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/feeding.rb
class Feeding < ApplicationRecord
  # Direct associations

  belongs_to :dog

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    dog.to_s
  end
end

app/controllers/api/v1/feedings_controller.rb
class Api::V1::FeedingsController < Api::V1::GraphitiController
  def index
    feedings = FeedingResource.all(params)
    respond_with(feedings)
  end

  def show
    feeding = FeedingResource.find(params)
    respond_with(feeding)
  end

  def create
    feeding = FeedingResource.build(params)

    if feeding.save
      render jsonapi: feeding, status: :created
    else
      render jsonapi_errors: feeding
    end
  end

  def update
    feeding = FeedingResource.find(params)

    if feeding.update_attributes
      render jsonapi: feeding
    else
      render jsonapi_errors: feeding
    end
  end

  def destroy
    feeding = FeedingResource.find(params)

    if feeding.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: feeding
    end
  end
end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController
  before_action :set_feeding, only: %i[show edit update destroy]

  def index
    @q = Feeding.ransack(params[:q])
    @feedings = @q.result(distinct: true).includes(:dog).page(params[:page]).per(10)
  end

  def show; end

  def new
    @feeding = Feeding.new
  end

  def edit; end

  def create
    @feeding = Feeding.new(feeding_params)

    if @feeding.save
      message = "Feeding was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @feeding, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @feeding.update(feeding_params)
      redirect_to @feeding, notice: "Feeding was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @feeding.destroy
    message = "Feeding was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to feedings_url, notice: message
    end
  end

  private

  def set_feeding
    @feeding = Feeding.find(params[:id])
  end

  def feeding_params
    params.require(:feeding).permit(:dog_id, :amount, :food_name)
  end
end

app/views/feedings/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Feeding #<%= feeding.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Dog</dt>
      <dd>
        <% if @feeding.dog.present? %>
          <%= link_to feeding.dog, feeding.dog %>
        <% end %>
      </dd>

      <dt>Amount</dt>
      <dd><%= feeding.amount %></dd>

      <dt>Food name</dt>
      <dd><%= feeding.food_name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back feeding, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_feeding_url(feeding), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to feeding, method: :delete, data: { confirm: "Do you really want to delete this feeding?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(feeding.updated_at) %> ago
  </div>
</div>

app/views/feedings/_feedings_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "feedings_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :food_name_cont, "Food name contains" %>
    <%= f.text_field :food_name_cont, :class => "form-control", :placeholder => "Food name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :amount_cont, "Amount contains" %>
    <%= f.text_field :amount_cont, :class => "form-control", :placeholder => "Amount contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :dog_name_cont, "Dog name contains" %>
    <%= f.text_field :dog_name_cont, :class => "form-control", :placeholder => "Dog name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/feedings" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#feedings_filters">
  Show filters
</a>

app/views/feedings/_form.html.erb
<% was_validated = feeding.errors.any? %>

<%= form_with(model: feeding, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% dog_class = "form-control" %>
    <% dog_was_invalid = feeding.errors.include?(:dog) %>

    <% if was_validated %>
      <% if dog_was_invalid %>
        <% dog_class << " is-invalid" %>
      <% else %>
        <% dog_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dog_id %>
    <%= f.collection_select :dog_id, Dog.all, :id, :to_s, {}, class: "form-control" %>
    <% if dog_was_invalid %>
      <% feeding.errors.full_messages_for(:dog).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% amount_class = "form-control" %>
    <% amount_was_invalid = feeding.errors.include?(:amount) %>

    <% if was_validated %>
      <% if amount_was_invalid %>
        <% amount_class << " is-invalid" %>
      <% else %>
        <% amount_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :amount %>
    <%= f.text_field :amount, class: amount_class, placeholder: "Enter amount" %>
    <% if amount_was_invalid %>
      <% feeding.errors.full_messages_for(:amount).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% food_name_class = "form-control" %>
    <% food_name_was_invalid = feeding.errors.include?(:food_name) %>

    <% if was_validated %>
      <% if food_name_was_invalid %>
        <% food_name_class << " is-invalid" %>
      <% else %>
        <% food_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :food_name %>
    <%= f.text_field :food_name, class: food_name_class, placeholder: "Enter food name" %>
    <% if food_name_was_invalid %>
      <% feeding.errors.full_messages_for(:food_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/feedings/_list_item.html.erb
<%= link_to feeding, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= feeding %>
    <small class="text-muted">
      <%= time_ago_in_words(feeding.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/feedings/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Feeding #<%= @feeding.id %>
      </h2>

      <div class="card-body">
        <%= render "form", feeding: @feeding %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/feedings/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Feedings

      <%= link_to new_feeding_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "feedings/feedings_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Feedings

        <%= link_to new_feeding_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @feedings, partial: "list_item", as: :feeding %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @feedings, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/feedings/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Feeding
      </h2>

      <div class="card-body">
        <%= render "form", feeding: @feeding %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/feedings/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @feeding, partial: "card", as: :feeding %>
  </div>
</div>